apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: client-eng-application
  app.kubernetes.io/instance: client-eng-application-instance
  app.kubernetes.io/name: client-eng-application